### ISSUE TITLE
End Bug

### ISSUE THREAD

**Issue by Kur0Daisuke** [SakutaTHZ/Shika-Typo#3]
i've finished typing but the game hasn't ended yet.

<img width="860" alt="Screenshot 2024-07-23 133017" src="https://github.com/user-attachments/assets/8ab18684-4314-4e85-b06a-313b1ee35a86">

**Comment by SakutaTHZ** [comment]
Fixed it partially

**Comment by SakutaTHZ** [comment]
It is fixed now
